//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishNoty.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishNoty.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///
        ///    &lt;SolidColorBrush x:Key=&quot;NormalBorderBrush&quot; Color=&quot;Black&quot; /&gt;
        ///    &lt;SolidColorBrush x:Key=&quot;DefaultedBorderBrush&quot; Color=&quot;Black&quot; /&gt;
        ///
        ///    &lt;SolidColorBrush x:Key=&quot;DisabledForegroundBrush&quot; Color=&quot;#888&quot; /&gt;
        ///
        ///    &lt;SolidColorBrush x:Key=&quot;DisabledBackgroundBrush&quot; Color=&quot;#EEE&quot; /&gt;
        ///
        ///    &lt;SolidColorBrush x:Key=&quot;DisabledBorderBrush&quot; Color=&quot;#AAA&quot; /&gt;
        ///
        ///    &lt;SolidC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ButtonStyle {
            get {
                return ResourceManager.GetString("ButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string DefaultListName {
            get {
                return ResourceManager.GetString("DefaultListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Lists.
        /// </summary>
        internal static string DefaultListStoreName {
            get {
                return ResourceManager.GetString("DefaultListStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionaries.
        /// </summary>
        internal static string Dictionaries {
            get {
                return ResourceManager.GetString("Dictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap facebook_button {
            get {
                object obj = ResourceManager.GetObject("facebook_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap microsoft_windows_8_logo {
            get {
                object obj = ResourceManager.GetObject("microsoft_windows_8_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entries.
        /// </summary>
        internal static string NEntries {
            get {
                return ResourceManager.GetString("NEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lists.
        /// </summary>
        internal static string NLists {
            get {
                return ResourceManager.GetString("NLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notification_icon {
            get {
                object obj = ResourceManager.GetObject("notification_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Radiation_warning_symbol {
            get {
                object obj = ResourceManager.GetObject("Radiation_warning_symbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Dictionaries.
        /// </summary>
        internal static string RecentDictionaries {
            get {
                return ResourceManager.GetString("RecentDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Lists.
        /// </summary>
        internal static string RecentListStoreName {
            get {
                return ResourceManager.GetString("RecentListStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
    }
}
